spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      pool:
        size: 10
  jackson:
    time-zone: Asia/Seoul

init:
  enabled : true

logging:
  file:
    name: /stock-logs/app.log # 이미 Dockerfile에서 -D로 설정했으므로 여기서는 선택 사항
  logback:
    rollingpolicy:
      max-file-size: 10MB # 각 로그 파일의 최대 크기
      max-history: 7 # 보관할 최대 파일 수
      total-size-cap: 100MB # 모든 보관된 로그 파일의 총 크기 제한

kis:
  clientId: ${KIS_CLIENT_ID}
  appkey: ${KIS_APP_KEY}
  appsecret: ${KIS_SECRET_KEY}
  grantType: client_credentials
  tokenUrl: https://openapi.koreainvestment.com:9443/oauth2/tokenP

server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8081

management:
  server:
    port: 9294
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true
data:
  service:
    key: 5n9IJueHw768SiRIOa9R0olMWrhJwyL7MizU9uL3DYjTmKZcW5z%2B%2F1M8mgyDI3WUcDa5kxgsSZj1tvdBjFOuRQ%3D%3D
