spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  data:
    redis:
      host: ${URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    url: jdbc:postgresql://${URL}/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      pool:
        size: 10

init:
  enabled : false



kis:
  clientId: ${KIS_CLIENT_ID}
  appkey: ${KIS_APP_KEY}
  appsecret: ${KIS_SECRET_KEY}
  grantType: client_credentials
  tokenUrl: https://openapi.koreainvestment.com:9443/oauth2/tokenP

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  server:
    port: 9293
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true
data:
  service:
    key: 5n9IJueHw768SiRIOa9R0olMWrhJwyL7MizU9uL3DYjTmKZcW5z%2B%2F1M8mgyDI3WUcDa5kxgsSZj1tvdBjFOuRQ%3D%3D
